# Generated by Django 6.0.8 on 2026-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contribution_start_date',
            field=models.DateField(default='2024-11-01', help_text='Date from which member contribution should be calculated '),
            preserve_default=False,
        ),
    ]
